---
abstract: 'An abstract Moose role for setting attributes from a configfile'
author:
  - 'Brandon L. Black, <blblack@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::Fatal: 0
  Test::More: 0.42
  Test::NoWarnings: 1.04
  Test::Requires: 0
  Test::Without::Module: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-ConfigFromFile
no_index:
  directory:
    - inc
    - t
requires:
  Moose: 0.35
  MooseX::Types::Path::Tiny: 0
  Try::Tiny: 0
  namespace::autoclean: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://git.moose.perl.org/MooseX-ConfigFromFile.git
version: 0.07
